/*
 *  Generated by `referee header` from examples/mctp/packet-records.ref.
 *  Do not edit: regenerate instead. Every entry point and type is
 *  prefixed `referee_`, so a `func` named `read` binds to
 *  `referee_read` and cannot reach read(2).
 */
#ifndef REFEREE_GENERATED_H
#define REFEREE_GENERATED_H

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

/*
 *  Arrays cross the boundary as a descriptor. `count` is the extent --
 *  the capacity -- not the meaningful length, so a caller with a shorter
 *  payload passes its own length as a separate argument and the callee
 *  can check it against `count`.
 */
typedef struct referee_slice_byte {
    size_t          count;
    const uint8_t*  data;
} referee_slice_byte;

/*  Implement these. The `referee_` prefix is part of the symbol name.  */

uint8_t referee_crc8(referee_slice_byte arg0,
                     int64_t arg1);


#ifdef __cplusplus
}
#endif
#endif  /* REFEREE_GENERATED_H */
